### ISSUE TITLE
fading issue with new zigbee 3.0 lights

### ISSUE THREAD

**Issue by Moumoustache** [home-assistant-libs/aiohue#14]
hey there,

i have a weird behaviour with new zigbee 3.0 lamps in my hue bridge. It seems for those new bulbs only, everytime i request a state change from home assistant it fades incorrectly (like it s dimming up and down before executing the targeted state)...the weirdest thing is, when i made a restful switch based on the hue api it works perfectly

that's the code of the restful switch. 
```
switch:
  - platform: rest
    method: put
    resource: http://192.168.0.10/api/rEE8fqPYSS9w4uRivOMpbyUtIkKP8BWtnD65HDrL/lights/10/state
    body_on: '{"on": true}'
    body_off: '{"on": false}'
```
I was suspecting a change in hue api impacting zigbee 3.0 lights only...any clue ?

Thx
